DROP TABLE orders IF EXISTS;
DROP TABLE currency IF EXISTS;
DROP TABLE DealerMoney IF EXISTS;
DROP TABLE Money IF EXISTS;
DROP TABLE Dealer IF EXISTS;

CREATE TABLE Dealer (
dealerID integer PRIMARY KEY,
firstName varchar(20),
lastName varchar(20),
info varchar(300)
);
INSERT INTO Dealer VALUES (1, 'John', 'Doe', 'super dealer');

CREATE TABLE Money (
moneyID char(3) PRIMARY KEY,
description varchar(20)
);
INSERT INTO Money VALUES ('eur', 'euro');
INSERT INTO Money VALUES ('usd', 'american dollar');

CREATE TABLE DealerMoney (
dealerID integer REFERENCES Dealer (dealerID),
moneyID char(3) REFERENCES Money (moneyID),
amount DECIMAL(15, 2),
PRIMARY KEY (dealerID, moneyID)
);
INSERT INTO DealerMoney VALUES (1, 'eur', 1000.00);
INSERT INTO DealerMoney VALUES (1, 'usd', 1000.00);

CREATE TABLE currency (
money1 char(3) REFERENCES Money (moneyID),
money2 char(3) REFERENCES Money (moneyID),
timestamp TIMESTAMP,
bid DECIMAL(10, 4),
ask DECIMAL(10, 4),
PRIMARY KEY (money1, money2)
);
INSERT INTO currency VALUES ('eur', 'usd', '2016-02-04 23:00:00', '1.0919', '1.0921');

CREATE TABLE orders (
orderID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
dealerID integer REFERENCES dealer (dealerID),
moneyToSell char(3) REFERENCES Money (moneyID),
moneyToBuy char(3) REFERENCES Money (moneyID),
buyAmount DECIMAL(15, 2),
sellAmount DECIMAL(15, 2),
rate DECIMAL(10, 4),
timestamp TIMESTAMP
);
